services:
  # Backend API Service (Already deployed at finance-backend-iela.onrender.com)
  - type: web
    name: finance-backend-iela
    env: node
    region: oregon
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: mongodb-atlas
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://rush-finance-app.onrender.com

  # Frontend Static Site
  - type: web
    name: rush-finance-app
    env: static
    region: oregon
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://finance-backend-iela.onrender.com/api